#!/bin/bash

set -e
set -x

gcc --version
g++ --version

rm -rf cmake-3.11.1
tar xzvf cmake-3.11.1.tar.gz
cd cmake-3.11.1 || exit
./configure
make -j4
cd ..

rm -rf m4ri-20200125
tar xzvf m4ri-20200125.tar.gz
cd m4ri-20200125 || exit
rm -rf myinstall
mkdir -p myinstall
./configure --prefix=$(pwd)/myinstall
make -j4 VERBOSE=1
make install
cd ..

rm -rf cms/build
rm -rf abc
rm -rf abc2
rm -rf xyz
mkdir cms/build

cd cms/build || exit
../../cmake-3.11.1/bin/cmake --version
M4RI_ROOT_DIR=$(pwd)/../../m4ri-20200125/myinstall ../../cmake-3.11.1/bin/cmake -DENABLE_PYTHON_INTERFACE=OFF -DNOVALGRIND=ON -DNOZLIB=ON -DONLY_SIMPLE=ON -DSTATICCOMPILE=ON -DCMAKE_BUILD_TYPE=Release -DENABLE_TESTING=OFF -DIPASIR=ON -DMANPAGE=OFF ..
make -j4 VERBOSE=1
cd ../..

# now create combined archive
cp cms/build/lib/libipasircryptominisat5.a .
cp cms/build/lib/libcryptominisat5.a .
mkdir abc; cd abc; ar -x ../libipasircryptominisat5.a; cd ..
mkdir abc2; cd abc2; ar -x ../libcryptominisat5.a; cd ..
mkdir xyz; cd xyz; ar -x ../m4ri-20200125/.libs/libm4ri.a; cd ..
rm libipasircryptominisat5.a
rm libcryptominisat5.a
ar -qc libipasircryptominisat5.a abc/* abc2/* xyz/*
rm -rf abc abc2 xyz
