#!/bin/bash

set -e
set -x

gcc --version
g++ --version

rm -rf cmake-3.11.1
tar xzvf cmake-3.11.1.tar.gz
cd cmake-3.11.1 || exit
./configure
make -j4
cd ..

rm -rf m4ri-20200125
tar xzvf m4ri-20200125.tar.gz
cd m4ri-20200125 || exit
rm -rf myinstall
mkdir -p myinstall
./configure --prefix=$(pwd)/myinstall
make -j4 VERBOSE=1
make install
cd ..

rm -rf cms/build
rm -rf abc abc2 abc3 abc4 abc5 abc6
mkdir cms/build

cd cms/build || exit
../../cmake-3.11.1/bin/cmake --version
M4RI_ROOT_DIR=$(pwd)/../../m4ri-20200125/myinstall ../../cmake-3.11.1/bin/cmake -DENABLE_PYTHON_INTERFACE=OFF -DNOVALGRIND=ON -DNOZLIB=ON -DONLY_SIMPLE=ON -DSTATICCOMPILE=ON -DCMAKE_BUILD_TYPE=Release -DENABLE_TESTING=OFF -DIPASIR=ON -DMANPAGE=OFF ..
make -j4 VERBOSE=1
cd ../..

# now create combined archive
cp cms/build/lib/libipasircryptominisat5.a .
cp cms/build/lib/libcryptominisat5.a .
mkdir abc;  cd abc;  ar -x ../libipasircryptominisat5.a; cd ..
# mkdir abc2; cd abc2; ar -x ../libcryptominisat5.a; cd ..
mkdir abc3; cd abc3; ar -x ../m4ri-20200125/.libs/libm4ri.a; cd ..
# mkdir abc4; cd abc4; ar -x /usr/lib/libstdc++.a; cd ..
# mkdir abc5; cd abc5; ar -x /usr/lib/libpthread.a; cd ..
# mkdir abc7; cd abc7; ar -x /usr/lib/libc.a; cd ..
# mkdir abc6; cd abc6; ar -x /usr/lib/libm.a; cd ..
rm libipasircryptominisat5.a
rm libcryptominisat5.a
ar -qc libipasircryptominisat5.a abc/* abc3/*
rm -rf abc abc2 abc3 abc4 abc6 abc7
