#!/bin/bash

set -e
set -x

rm -rf bin/crypto*
rm -rf myinstall

gcc --version
g++ --version

# build cmake
rm -rf cmake-3.11.1
tar xzvf cmake-3.11.1.tar.gz
cd cmake-3.11.1 || exit
./configure
make -j4
cd ..

# build m4ri
rm -rf m4ri-20200125
tar xzvf m4ri-20200125.tar.gz
cd m4ri-20200125 || exit
rm -rf myinstall
mkdir -p myinstall
./configure --prefix=$(pwd)/myinstall
make -j4 VERBOSE=1
make install
cd ..

#check cmake
../../cmake-3.11.1/bin/cmake --version

# build breakid
rm -rf breakid/build
mkdir breakid/build
cd breakid/build || exit
../../cmake-3.11.1/bin/cmake -DSTATICCOMPILE=ON -DCMAKE_BUILD_TYPE=Release ..
make -j4 VERBOSE=1
cd ../..


# build cms
rm -rf cms/build
mkdir cms/build
cd cms/build || exit
M4RI_ROOT_DIR=$(pwd)/../../m4ri-20200125/myinstall ../../cmake-3.11.1/bin/cmake -DENABLE_PYTHON_INTERFACE=OFF -DNOVALGRIND=ON -DNOZLIB=ON -DONLY_SIMPLE=ON -DSTATICCOMPILE=ON -DCMAKE_BUILD_TYPE=Release -DENABLE_TESTING=OFF -DMANPAGE=OFF ..
make -j4 VERBOSE=1
cp cryptominisat5_simple ../../bin/
ldd ./cryptominisat5_simple || true
echo "1 0" | ./cryptominisat5_simple || true
echo "1 0" | ./cryptominisat5_simple --sls=ccnr || true
echo "1 0" | ./cryptominisat5_simple --sls=walksat || true
cd ../..
