#!/bin/bash

set -e
set -x

rm -rf bin/crypto*
rm -rf myinstall

gcc --version
g++ --version

rm -rf cmake-3.11.1
tar xzvf cmake-3.11.1.tar.gz
cd cmake-3.11.1 || exit
./configure
make -j4
cd ..

rm -rf m4ri-20200125
tar xzvf m4ri-20200125.tar.gz
cd m4ri-20200125 || exit
rm -rf myinstall
mkdir -p myinstall
./configure --prefix=$(pwd)/myinstall
make -j4 VERBOSE=1
make install
cd ..

rm -rf cms/build
mkdir cms/build

cd cms/build || exit
../../cmake-3.11.1/bin/cmake --version
M4RI_ROOT_DIR=$(pwd)/../../m4ri-20200125/myinstall ../../cmake-3.11.1/bin/cmake -DENABLE_PYTHON_INTERFACE=OFF -DNOVALGRIND=ON -DNOZLIB=ON -DONLY_SIMPLE=ON -DSTATICCOMPILE=ON -DCMAKE_BUILD_TYPE=Release -DENABLE_TESTING=OFF -DMANPAGE=OFF -DUSE_GAUSS=ON ..
make -j4 VERBOSE=1
cp cryptominisat5_simple ../../bin/
ldd ./cryptominisat5_simple || true
echo "1 0" | ./cryptominisat5_simple || true
echo "1 0" | ./cryptominisat5_simple --sls=ccnr || true
echo "1 0" | ./cryptominisat5_simple --sls=walksat || true
